name: 运行nextjs和cpolar

on:
  # 手动触发
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出主仓库
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2. 环境准备
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3. 运行 Next.js (Standalone 模式)
      - name: 下载 rendie-nextjs
        uses: actions/checkout@v4
        with:
          repository: rendie-com/rendie-nextjs
          token: ${{ secrets.MY_PAT }}
          path: rendie-nextjs
          fetch-depth: 1

      - name: 启动 Next.js
        run: |   
          cd ./rendie-nextjs/
          pnpm i
          pnpm run dev & 
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PROXY_URL: ${{ secrets.PROXY_URL }}
          NEXTJS_CONFIG_DEFAULT_DB: ${{ secrets.NEXTJS_CONFIG_DEFAULT_DB }}  
          NEXTJS_CONFIG_PG01: ${{ secrets.NEXTJS_CONFIG_PG01 }}  
          NEXTJS_CONFIG_PG02: ${{ secrets.NEXTJS_CONFIG_PG02 }} 
          NEXTJS_CONFIG_SQLITE: ${{ secrets.NEXTJS_CONFIG_SQLITE }} 

      - name: 下载【rendie-node】仓库
        run: |        
          mkdir -p ./sqlite3/error/ 
          git clone https://github.com/rendie-com/rendie-node -b main ./node

      - name: 运行 cpolar       
        run: |     
          unzip ./node/cpolar-stable-linux-amd64.zip       
          chmod a+rwx ./cpolar
          ./cpolar authtoken ${{ secrets.CPOLAR_AUTHTOKEN }}  
          echo "已授权"
          ./cpolar http 3000 &
     
      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        
      - name: 部署[sqlite3/]目录
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
            branch: main
            folder: sqlite3/
            target-folder: sqlite3/
   
