name: 2.shopee-保持在线-置顶推广-5分钟

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write
  actions: write

env:   
  TZ: Asia/Shanghai
  NODE_USERNAME: "5minute"
  NODE_ACCESS_TOKEN: ${{ secrets.NODE_ACCESS_TOKEN_2 }}
  NODE_REFRESH_TOKEN: ${{ secrets.NODE_REFRESH_TOKEN_2 }}
  NODE_EXPIRES_IN: "1777047860"
  MAX_RUNTIME_MINUTES: 2
  TARGET_DIR: "error/task2"
  GITHUB_TOKEN: ${{ secrets.MY_PAT }}
  GITHUB_OWNER: "rendie-com"
  GITHUB_REPO: "rendie-node.js-error"
  NODE_MENU_LIST: '{"top1":1,"top2":{"23":{"name":"任务","id":"23","isbool":true,"url":"http://localhost:3000/view/Default/admin/html/iframe.html?template=Shopee/任务/index.js&jsFile=js02&return=%2Fview%2FDefault%2Fadmin%2Fhtml%2Fiframe.html%3Ftemplate%3DShopee%2F%25E4%25BB%25BB%25E5%258A%25A1%2Findex.js%26jsFile%3Djs04"}}}'

jobs:
  automation_job:
    runs-on: ubuntu-latest
    steps:
      - name: 1. 下载代码
        uses: actions/checkout@v6

      - name: 2. 下载核心代码
        uses: actions/checkout@v6
        with:
          repository: rendie-com/rendie-next.js
          token: ${{ secrets.MY_PAT }}
          path: next.js

      - name: 3. 下载sqlite3数据库
        uses: actions/checkout@v6
        with:
          repository: rendie-com/rendie-sqlite3-system
          token: ${{ secrets.MY_PAT }}
          path: sqlite3
        
      - name: 4. 安装 Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          # 更新缓存路径
          cache-dependency-path: |
            node.js/package-lock.json
            next.js/package-lock.json

      - name: 5. 并行安装与启动 (极致加速)
        run: |       
          mv ./sqlite3/sqlite3/* ./sqlite3/ 2>/dev/null || true
          # A. 并行安装依赖
          npm ci --prefix node.js --prefer-offline --no-audit &
          PID_MAIN=$!
          
          npm ci --prefix next.js --prefer-offline --no-audit &
          PID_NEXT=$!
          
          # B. 等待安装任务完成
          wait $PID_MAIN $PID_NEXT
          
          echo "✅ 依赖就绪，开始运行..."
          
          # C. 启动前端 Next.js 服务 (使用 next.js 目录)
          npm run dev --prefix next.js & 
          
          # D. 预留启动时间
          sleep 10
          
          # E. 启动后端主程序
          cd node.js && npm run start
        env:
          NEXTJS_CONFIG_DEFAULT_DB: ${{ secrets.NEXTJS_CONFIG_DEFAULT_DB }}  
          NEXTJS_CONFIG_SQLITE: ${{ secrets.NEXTJS_CONFIG_SQLITE }}