name: aaaaa

on:
  workflow_dispatch: 

permissions:
  contents: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出当前仓库
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 运行 粉丝-聊聊 脚本
        run: |
               mkdir -p error/
               echo "Last Run: $(date)" > error/syn8888888888888888888888c-check.txt
                
      # 7. 部署到 main 分支 🚀
      - name: Deploy to Main 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: error
          branch: master
          target-folder: error
          commit-message: "data: 自动更新数据并保留源码 [skip ci]" # 👈 必须带 [skip ci] 防止死循环