name: aaaaa

on:
  workflow_dispatch: 

permissions:
  contents: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出当前仓库
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 恢复数据库缓存        
        uses: actions/cache@v3
        with:
          path: bbb
          key: db-aaaa-${{ github.run_id }}         

      - name: 4. (备选) 下载初始数据库仓库
        if: hashFiles('aaaa/**') == ''
        uses: actions/checkout@v6
        with:
          repository: rendie-com/rendie-sqlite3-system
          token: ${{ secrets.MY_PAT }}
          path: bbb
          fetch-depth: 1